language: go

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
    - GO111MODULE=on

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
    - 1.11.x

# Only clone the most recent commit.
git:
    depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
    email: false

# script always runs to completion.
script:
    - go test -v -race ./... # Run all the tests with the race detector enabled
